name: Deploy to server

on:
  push:
    branches: [main, stage]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install

      - name: Run build
        env:
          NODE_ENV: production
        run: |
          unset CI
          npm run build

      - name: Sync Files
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -hvrPt --exclude=".git" --exclude="node_modules"
          remote_path: /fileserver
          remote_host: 34.219.78.65
          remote_user: ubuntu
          remote_key: ${{ secrets.EC2_SSH_KEY }}
